### ISSUE TITLE
nsml graph session does not work 

### ISSUE THREAD

**Issue by JongSuk1** [Naver-AI-Hackathon/cs492I#11]
I used nsml.report function as below by following uploaded nsml lecture.
`            if IS_ON_NSML:
                nsml.report(summary={
                    'train_epoch/loss': loss,
                    'train_epoch/acc_train_top1': train_top1,
                    'train_epoch/acc_train_top5': train_top5,
                    'test_epoch/acc_val_top1': acc_top1,
                    'test_epoch/acc_val_top5': acc_top5},
                    step=epoch)`
It didn't make any error and I can see some scalar data loading when graph session clicked.
However, after session finsihed, it doesn't make any graph.

Is there any problem with my code??

**Comment by bluebrush** [comment]
Could you show your sessionID?

**Comment by JongSuk1** [comment]
It is "kaist_12/fashion_eval/3"

**Comment by nsml-admin** [comment]
It looks like the session (`kaist_12/fashion_eval/3`) does not contain any metric for the `y-value` (it only contains metric for `x-value`), so please check `nsml.report` is working properly in your code.

I attach the session log as below.

```
nsml events kaist_12/fashion_eval/3
INFO[2020/04/22 16:59:16.469] ****************************************************************************** 
INFO[2020/04/22 16:59:16.469] * Interactive session will be terminated automatically after 30 minutes      * 
INFO[2020/04/22 16:59:16.470] * If you don't want to see this message, please use --hide-client-log option * 
INFO[2020/04/22 16:59:16.470] ****************************************************************************** 
{"data": {"step": 0, "walltime": 1587466880.6224372}}
{"data": {"step": 1, "walltime": 1587466882.804386}}
{"data": {"step": 2, "walltime": 1587466884.7464457}}
{"data": {"step": 3, "walltime": 1587466886.7164898}}
{"data": {"step": 4, "walltime": 1587466888.6857274}}
{"data": {"step": 5, "walltime": 1587466890.7355094}}
{"data": {"step": 6, "walltime": 1587466892.7111166}}
{"data": {"step": 7, "walltime": 1587466894.784139}}
{"data": {"step": 8, "walltime": 1587466896.8034778}}
{"data": {"step": 9, "walltime": 1587466898.842333}}

...
```
