### ISSUE TITLE
Error in putting the model into the Leaderboard

### ISSUE THREAD

**Issue by erjui** [Naver-AI-Hackathon/cs492I#12]
I tried with the baseline code given on the notice board.
And It seems it worked well as I saw the terminal log.

But after running, there's no model when I pull it into my local file system.
Even my model has not been updated in the Leaderboard.

So I want to know how to handle this.

My session was kaist_9/fashion_eval/2 for reference...

Thanks in advance :)

**Comment by nsml-admin** [comment]
You can download your model using `nsml model pull` command

ex) `nsml model pull kaist_9/fashion_eval/2 Res18baseMM_e199 ./`
