### ISSUE TITLE
Submission of the model

### ISSUE THREAD

**Issue by erjui** [Naver-AI-Hackathon/cs492I#14]
Hi, sorry to ask this kind of simple question. 
But I'm asking this because I'm having a hard time even running the baseline code.
I just ran the baseline code to train the model as follows.

`nsml -d fashion_eval -e main.py`

And I got the following terminal log as a result.

![image](https://user-images.githubusercontent.com/36221725/79967972-7f2ae800-84ca-11ea-850d-ef2d9083555e.png)

First, I want to ask why the segmentation fault happened even after running the baseline code that I didn't modify... (I tried to fix on my own but couldn't find it, and I think it would be better to ask here because many teams already succeed to run the baseline code already!)

Despite the segmentation fault, since the model itself was successfully saved, I tried to submit with the following command too.

`nsml submit -t kaist_9/fashion_eval/2 Res18baseMM_best`

But I also ran into the following error....

![image](https://user-images.githubusercontent.com/36221725/79968643-60792100-84cb-11ea-9223-fc18bccb1fc5.png)

So I want to ask how to solve this question.

Thanks in advance, and sorry for asking this kind of simple question.

**Comment by nsml-admin** [comment]
'segment related error' is mostly a memory related error.

When you type `nsml run`, allocate more memory with the `--memory` option or code it in a way that uses less memory in the code (for example, to reduce the batch size).

**Comment by erjui** [comment]
> 'segment related error' is mostly a memory related error.
> 
> When you type `nsml run`, allocate more memory with the `--memory` option or code it in a way that uses less memory in the code (for example, to reduce the batch size).

Umm.. I am not sure, but I think it's not the problem of running out of memory.
For clarifying this. I slightly modified source code that it only runs 1 epoch with batch size 128.
And I add a print message after main function ends like follows.

![image](https://user-images.githubusercontent.com/36221725/80063342-af2cc680-8570-11ea-9d5a-7d2fed236bcf.png)

![image](https://user-images.githubusercontent.com/36221725/80064644-7cd09880-8573-11ea-8398-319c4f821603.png)


But the result was segmentation fault again as follows.

![image](https://user-images.githubusercontent.com/36221725/80063967-04b5a300-8572-11ea-933a-848c527d223a.png)

Since "the program ends" log appeared in the terminal log.
I carefully guess my code part itself ran successfully.

After all, model was successfully saved as the message shows though segmentation fault happened.
So I also tried to submit the model into the Leaderborad.
Then also segmentation fault happened as follows.

![image](https://user-images.githubusercontent.com/36221725/80064617-69253200-8573-11ea-8321-ea274e040d53.png)


![image](https://user-images.githubusercontent.com/36221725/80064434-016ee700-8573-11ea-927c-ae3746292619.png)

Even testing the result with successfully saved model failed with segmentation fault...

Thanks in advance!

**Comment by nsml-admin** [comment]
It looks like you have a problem using an older version of Python or docker. Please refer to [here](https://github.com/GitGyun/CS492H_NSML_Project1_Baselline/pull/2/files) and replace the default docker image with nvcr.io/nvidia/pytorch:20.03-py3 and try again.
