### ISSUE TITLE
Session is kept running when submitting the result

### ISSUE THREAD

**Issue by trtrung** [Naver-AI-Hackathon/cs492I#15]
When I tried to submit the session, there is no result was returned. However, these sessions are kept running and each of them takes one GPU.
![image](https://user-images.githubusercontent.com/62499629/80123429-da8fcf80-85c9-11ea-82e7-2c2ac731525f.png)
I cannot stop or remove these two sessions.
**Could you help me remove these two sessions because they are taking our 2 GPUs?**

**Comment by trtrung** [comment]
Status of these two sessions become **Zombie** like:
![image](https://user-images.githubusercontent.com/62499629/80165392-5adc2200-8616-11ea-9ec1-e7749aa7439b.png)

**Comment by nsml-admin** [comment]
Deleted those sessions.

You can delete your session using `nsml rm -f `command in Command Line Interface.(CLI)

ex. `nsml rm -f kaist_2/fashion_eval/13 kaist_2/fashion_eval/11`
