### ISSUE TITLE
How could I update a file (e.g. main.py) in a session which already ran before?

### ISSUE THREAD

**Issue by trtrung** [Naver-AI-Hackathon/cs492I#17]
I made some modifications in the model, and the input of ```forward()``` was changed. 
Actually, my session is already done. However, I forgot to modify ```_infer()``` function of NSML of ```main.py```, so I cannot submit that session.
Re-training the model is not a good solution because it took more than 2 days, so how could I make an update to this file?

**Comment by nsml-admin** [comment]
See the link below.

https://n-clair.github.io/ai-docs/_build/html/en_US/contents/load_model.html
https://github.com/ai-starthon/AI_Starthon2019/issues/124

**Comment by trtrung** [comment]
Thank you!
