### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by as12088** [Naver-AI-Hackathon/cs492I#20]
RuntimeError: CUDA out of memory. Tried to allocate 1.79 GiB (GPU 0; 23.88 GiB total capacity; 22.20 GiB already allocated; 560.88 MiB free; 567.27 MiB cached)

How can I hold it?

**Comment by bluebrush** [comment]
What is your session?

**Comment by as12088** [comment]
kaist_14/fasion_eval/85 and kaist_14/fasion_eval/87
