### ISSUE TITLE
How to check the model list before creating team account?

### ISSUE THREAD

**Issue by yoonkicho** [Naver-AI-Hackathon/cs492I#21]
Hi, we're team kaist_6, thanks for your GPU supporting.

I want to check&get the model before creating team account, so I tried the following in Linux terminal and got errors.
```
>>> nsml model ls choyoonki/fashion_eval/
>>> FATA[2020/04/28 17:16:06.858] You cannot use this command for the other's session.
```

I think it caused by accessing my previous session through our team account.
**1. How can I check the model list? I want to evaluate our model on local.**

**2. Also, there are the ways to evaluate the model in private? (private submit?)**

Thanks!

**Comment by nsml-admin** [comment]
1. You can check model list using `nsml model ls [session]` command. You can't evaluate model on local machine
    ex) `nsml model ls kaist_6/fashion_eval/7`
2. There's no way to evaluate in private.

**Comment by yoonkicho** [comment]
> 1. You can check model list using `nsml model ls [session]` command. You can't evaluate model on local machine
>    ex) `nsml model ls kaist_6/fashion_eval/7`
> 2. There's no way to evaluate in private.

Thanks for reply!
About answer 1, how can I check the model list from the session that is before creating team account? ex) `nsml model ls choyoonki/fashion_eval/6`
It returns the message `FATA[2020/04/28 17:16:06.858] You cannot use this command for the other's session.`

**Comment by nsml-admin** [comment]
Sessions created before the team was created are not accessible.

**Comment by yoonkicho** [comment]
I see, thanks!
