### ISSUE TITLE
How to plot graph in nsml

### ISSUE THREAD

**Issue by as12088** [Naver-AI-Hackathon/cs492I#22]
There are no such specific example for this 

nsml.report(summary=False, scope=None, **kwargs)

Can you please explain how to handle nsml report to plot graph? 

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
            nsml.report(summary={
                ’train__loss__acc’: acc_top1,
                ’train__loss__avg’ : loss_avg},
                step=epoch)
I used like this in session kaist_14/fashion_eval/98

**Comment by nsml-admin** [comment]
Please change it as below.
```python
nsml.report(summary=True, ’train__loss__acc’= acc_top1, ’train__loss__avg’=loss_avg, step=epoch)
```

See also [documentation](https://n-clair.github.io/ai-docs/_build/html/en_US/contents/nsml_library/nsml_report.html)

**Comment by as12088** [comment]
File "main.py", line 305
    nsml.report(summary=True,'train__loss__acc'= acc_top1, 'train__loss__avg'=loss_avg, step=epoch)
                            ^
SyntaxError: keyword can't be an expression

This kind of error occurs
session : kaist_14/fashion_eval/125

**Comment by nsml-admin** [comment]
sorry I was mistaken. Try like below.

```python
nsml.report(summary=True, train__loss__acc=acc_top1, train__loss__avg=loss_avg, step=epoch)
```
