### ISSUE TITLE
Model submission error

### ISSUE THREAD

**Issue by as12088** [Naver-AI-Hackathon/cs492I#23]
(core dumped) python -u main.py --batchsize 50 --lr 1e-4 --mode test --pause 1

Session : kaist_14/fashion_eval/127

When I try to submit pretrained model, it always fail
I can i solve it?

**Comment by nsml-admin** [comment]
The problem of this error is docker image. 
Please change docker image.

refer to this
https://github.com/GitGyun/CS492H_NSML_Project1_Baselline/blob/master/requirements.txt

**Comment by as12088** [comment]
After changing requirements.txt, I still have the problem

session : kaist_14/fashion_eval/141

**Comment by nsml-admin** [comment]
`nsml submit` copies and evaluate the original session. Therefore, you need to re-run the new session with changed docker image and submit it

**Comment by as12088** [comment]
I re-run a new session and submit a model from the new session, but still got problem.
Session: kaist_14/fashion_eval/151
