### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by erjui** [Naver-AI-Hackathon/cs492I#26]
I got an error as follows.

RuntimeError: CUDA out of memory. Tried to allocate 126.00 MiB (GPU 0; 23.88 GiB total capacity; 23.02 GiB already allocated; 14.88 MiB free; 23.25 GiB reserved in total by PyTorch)

First I thought this is just because of the large batch size or large size of base model.
But the problem is that the error occurs sometimes and doesn't occur sometimes.
Even I didn't get this kind of error one time and got error later with the same image size, same batch size, same base model architecture.

Thanks in advance.

**Comment by erjui** [comment]
OSError: [Errno 28] No space left on device

Even I just got this kind of error which shouldn't appear..

**Comment by nsml-admin** [comment]
please let me know your session names
