### ISSUE TITLE
Referring wrong path during submit

### ISSUE THREAD

**Issue by DonghyunAhn** [Naver-AI-Hackathon/cs492I#27]
Hello, this is team 8, and we tried to test simple model we made by nsml run.
However, when we evaluate it, the error which was not rasied during traing step occurs about file path.
This is what we received from error message:
![image](https://user-images.githubusercontent.com/26649926/80861399-4bf60f00-8ca9-11ea-9dac-8cdff5dba660.png)

How can we handle this error?

**Comment by nsml-admin** [comment]
Because evaluation is performed in an independent container without a train dataset,

Changing the code to not access the `train dataset` before the `nsml.pause()` function seems to solve the problem.

**Comment by DonghyunAhn** [comment]
Then do we need to run another session to modify main.py here?
Or is there any way to change the code that already uploaded on previous session?

**Comment by nsml-admin** [comment]
You can change code that already uploaded session.

Please check this [issue](https://github.com/Naver-AI-Hackathon/cs492h/issues/17)
