### ISSUE TITLE
Downloading models from NSML

### ISSUE THREAD

**Issue by komfkore** [Naver-AI-Hackathon/cs492I#28]
NSML 에서 학습시킨 모델을 중간에 nsml.save를 통해서 nsml에 저장하고 있는데, 이 모델들을 로컬에 다운받을 수 있는 기능이 있나요?

**Comment by nsml-admin** [comment]
https://github.com/Naver-AI-Hackathon/cs492h/issues/12#issuecomment-617614346 를 참고해보시기 바랍니다.

**Comment by yoonkicho** [comment]
> [#12 (comment)](https://github.com/Naver-AI-Hackathon/cs492h/issues/12#issuecomment-617614346) 를 참고해보시기 바랍니다.

안녕하세요, 모델 다운로드를 위해 답변주신대로 입력하였으나 nsml model command에 대한 설명만 리턴되고 있습니다.

![image](https://user-images.githubusercontent.com/39462081/80940446-ca25f300-8e1a-11ea-958e-b42748e27c1b.png)

어떤식으로 해결할 수 있을까요?

**Comment by nsml-admin** [comment]
팀으로 로그인후에 다시 사용해 보실래요?  (아마 다시 로그인 하시면 될거같습니다)

**Comment by yoonkicho** [comment]
@nsml-admin 
> 팀으로 로그인후에 다시 사용해 보실래요? (아마 다시 로그인 하시면 될거같습니다)

공지된 바에 따르면, 개인 깃허브 계정을 통해 로그인하면 자동으로 팀계정으로 넘어간다고 하였습니다.!
그래서 개인 깃허브 계정으로 다시 로그인하였고, 시도하였으나 동일한 문제가 발생하는 중입니다.

혹시 팀계정으로 로그인하는 다른 방법이 있나요?

**Comment by nsml-admin** [comment]
`nsml whoami` 라고 치면 어떻게 나오나요?

**Comment by yoonkicho** [comment]
kaist_6 라고 나옵니다.

nsml pull -f SESSION TARGET 의 명령같은 경우는 잘 작동하고 있습니다!

**Comment by komfkore** [comment]
제 경우에도 작동하지 않는것 같습니다

**Comment by nsml-admin** [comment]
유저의 권한 레벨에따라서 사용할수 있는 명령어가 제한되어있는걸 착각한거같습니다. (죄송합니다)

`nsml pull` 명령어는 본인이 올린 코드만 다운받는것이라 제한이 없지만 `nsml model pull`은 세션을 실행후에 생성된 모델을 받는것이라 보안때문에 명령어를 지원하지 않았습니다 (모든 팀이 사용할수 없는 상황입니다)

`model pull` 명령어가 꼭 필요하다고 판단되면 운영진들과 상의후에 지원하도록 하겠습니다.

**Comment by yoonkicho** [comment]
NSML 에서 학습된 모델을 다운받을 수 있으면, failure case를 분석하는 등 다양하게 활용할 수 있을 것 같습니다. 친절한 답변 감사드립니다!
