### ISSUE TITLE
How could I download a pre-trained model on NSML using wget?

### ISSUE THREAD

**Issue by trtrung** [Naver-AI-Hackathon/cs492I#29]
I need to download the pre-trained model on NSML using ```wget``` command. However, I got the error:
```
wget: command not found
```
How could I solve this kind of problem?

**Comment by nsml-admin** [comment]
You need to install `wget` command.
libraries can be installed via [nsml_package.txt](https://n-clair.github.io/ai-docs/_build/html/en_US/contents/session/prepare_a_session_environment.html)

**Comment by trtrung** [comment]
Thank you!
