### ISSUE TITLE
We still cannot use multi gpu

### ISSUE THREAD

**Issue by DonghyunAhn** [Naver-AI-Hackathon/cs492I#30]
As one of my teammates(Sungwon-Han) uploaded the same issue at the comment of #25, our session cannot allocate the GPU resource as the course suggested (we request for 4 GPUs). 

When we run the code with  nsml run -d fashion_eval -g 4, then it just refuses allocating GPU and exit session.

**Comment by nsml-admin** [comment]
Since NSML has 1 GPU per node, We cannot assign  2 or more GPUs in one session.
Please note that only one gpu can be used per session.

**Comment by DonghyunAhn** [comment]
Then how can we use multi-gpu? We got a guide that each team can use 5GPUs.

**Comment by DonghyunAhn** [comment]
![image](https://user-images.githubusercontent.com/26649926/80938992-086ce380-8e16-11ea-80cd-57aaf322f56a.png)
So you mean that this notice was about we can run 5 sessions in parallel?

**Comment by nsml-admin** [comment]
Yes, It means you can run up to 5 sessions(each use 1GPU) in parallel.
