### ISSUE TITLE
how to use nsml.load() function properly? 

### ISSUE THREAD

**Issue by nkwook** [Naver-AI-Hackathon/cs492I#31]
Hello? our team is trying to use nsml.load() function to use trained model from our code.

We checked load is succeed, but problem occurs when our program tries to use that model.

Is there possible approach to solve this error?

Error code:
![image](https://user-images.githubusercontent.com/47589404/81058765-0d12c400-8f0a-11ea-94ca-97d63cd21769.png)

Our load code:
        simclr_model=nsml.load(checkpoint='SimCLR_e200_e60', session='kaist_4/fashion_eval/289')

Saved model in path:
![image](https://user-images.githubusercontent.com/47589404/81058890-56631380-8f0a-11ea-9af4-fedd8f990b8b.png)

Thanks for your help.

**Comment by nsml-admin** [comment]
`nsml.load()` has no return value, so you should not assign the function's return value to a variable.

It is a task to load parameters into the model in the bind_nsml function, so you just call `nsml.load()` is done

ex)
```python
     if IS_ON_NSML:
         bind_nsml(simclr_model)
         if opts.pause:
             nsml.paused (scope=locals())
     if IS_ON_NSML:
         nsml.load(checkpoint = 'SimCLR_e200_e60', session = 'kaist_4/fashion_eval/289')
     else:
         simclr_model, _, _ = load_model (opts, reload_model = True)

```

See also : https://n-clair.github.io/ai-docs/_build/html/en_US/contents/load_model.html

**Comment by nkwook** [comment]
thank u so much!
