### ISSUE TITLE
Cannot stop NSML session 

### ISSUE THREAD

**Issue by tzs930** [Naver-AI-Hackathon/cs492I#35]
Hi, I  have some problems when I try to stop NSML sessions.
When I use `nsml stop` command, I got following error messages from NSML :

```
$ nsml stop kaist_9/korquad-open-ldbd/17
Error: Docker daemon timeout!
FATA[2020/06/14 00:34:50.759] Internal server error 
```

Even in NSML browser console, I cannot stop sessions, and it prints same above messages on the console window.

**Comment by bluebrush** [comment]
@tzs930 . 
The inquired session is currently finished.
It was confirmed that there was a problem with the communication status between internal DBs.
