### ISSUE TITLE
Cannot stop the session

### ISSUE THREAD

**Issue by komfkore** [Naver-AI-Hackathon/cs492I#36]
Hello, we're team 15 and we cannot remove our session which is running. (even with rm -f command)

Session's name is kairt_15/korquad-open-ldbd/396. 

It also doesn't show anything in terminal except "Error: Docker daemon timeout!" this error message. 

How can we resolve this issue? thanks.

**Comment by bluebrush** [comment]
@chocolatefudge 
The inquired session was not running, and the session has been deleted.
It is confirmed that there is a problem in the communication status between internal DBs, and the correction code is reflected.
