### ISSUE TITLE
Can you add apex library in default docker image?

### ISSUE THREAD

**Issue by kboseong** [Naver-AI-Hackathon/cs492I#4]
To improve efficiency of the gpus, I think apex library is necessary.
Thank you for the great baseline work.

**Comment by nsml-admin** [comment]
Hi! This NSML team.

If you need APEX library and NVIDIA add-ons, please use NGC docker images.
NGC provides APEX installed docker images.

#### In requirements.txt or setup.py
``` 
#nsml: nvcr.io/nvidia/pytorch:19.10-py3
...
```

#### References
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/running.html

**Comment by kboseong** [comment]
> Hi! This NSML team.
> 
> If you need APEX library and NVIDIA add-ons, please use NGC docker images.
> NGC provides APEX installed docker images.
> 
> #### In requirements.txt or setup.py
> ```
> #nsml: nvcr.io/nvidia/pytorch:19.10-py3
> ...
> ```
> 
> #### References
> https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/running.html

Thank you for your response.
I didn't know nsml had that kind of function.
Thank you!!
