### ISSUE TITLE
Is it allowed to save preprocessed data?

### ISSUE THREAD

**Issue by ChoiIseungil** [Naver-AI-Hackathon/cs492I#53]
We would like to save preprocessed data because preprocessing precedure takes too long.
Are we allowed to save only models? If there is a way, please let me know.
Thank you.

**Comment by bluebrush** [comment]
How big is it you want to store?

**Comment by ChoiIseungil** [comment]
We suppose it will be around 2.8G(just as original dataset). We have tried to do with nsml.save, but I wonder if this can only save the model checkpoint.
