### ISSUE TITLE
Setting an environment

### ISSUE THREAD

**Issue by erjui** [Naver-AI-Hackathon/cs492I#8]
Sorry to ask this kind of question because it seems everyone already knows how to set the environment, but I am having a hard time how I can use requirements.txt and setup.py.
As far as I understand, requirements.txt and setup.py can be used to set up the same developing environment between mine and server (nsml in this case). But the problem is that nsml server uses python 3.5 as base python version, that the server cannot even download proper packages I have even if I specify the version of packages in my environment (which I set as python 3.6).
To handle this, also as I understand, docker can be the easiest solution because all I have to do is just specify the docker image in the requirements.txt or setup.py. (I'm now assuming that this docker image contains proper python version as well as required packages to run the baseline code, tho not sure..)
So I tried this by adding requirements.txt file and contents as follows.
`#nsml: nvcr.io/nvidia/pytorch:19.10-py3`
But it seems nsml failed to detect docker image to set the environment probably because I didn't specify enough information in somewhere I don't know.

And even after solving the environment issue, is it right to use only the following one-line command to test a baseline code? (I mean this code is enough for my model to be included in the leaderboard?)
`nsml run -b fashion_eval -e mixmatch_train.py`

Answer this as detail as possible if you can, please...
It's my first time to use docker so don't know how it works well.
Thanks in advance :P

**Comment by nsml-admin** [comment]
I guess the problem with `#nsml: nvcr.io/nvidia/pytorch:19.10-py3` is about to authenticate.
NSML is try to pulling Docker image from GPU server but has no authority for that image.(maybe all nvcr related docker images have same problem)
We will figure out how to fix it. until then please use other Docker image from DockerHub.

`nsml run -d fashion_eval -e mixmatch_train.py` is right command for using fashion_eval data.(not `-b` option)

And I heard that [baseline code](https://github.com/GitGyun/CS492H_NSML_Project1_Baselline) need to delete [`pytorch_metric_learning`](https://github.com/GitGyun/CS492H_NSML_Project1_Baselline/blob/master/main.py#L31-L32) related code for working in NSML

Thank you.
